pycallgraph graphviz --dot-file dynamicCGs/dependency_injection.dot -- ./patterns/dependency_injection.py
pycallgraph graphviz --dot-file dynamicCGs/blackboard.dot -- ./patterns/other/blackboard.py
pycallgraph graphviz --dot-file dynamicCGs/hsm.dot -- ./patterns/other/hsm/hsm.py
pycallgraph graphviz --dot-file dynamicCGs/graph_search.dot -- ./patterns/other/graph_search.py
pycallgraph graphviz --dot-file dynamicCGs/abstract_factory.dot -- ./patterns/creational/abstract_factory.py
pycallgraph graphviz --dot-file dynamicCGs/factory.dot -- ./patterns/creational/factory.py
pycallgraph graphviz --dot-file dynamicCGs/builder.dot -- ./patterns/creational/builder.py
pycallgraph graphviz --dot-file dynamicCGs/lazy_evaluation.dot -- ./patterns/creational/lazy_evaluation.py
pycallgraph graphviz --dot-file dynamicCGs/prototype.dot -- ./patterns/creational/prototype.py
pycallgraph graphviz --dot-file dynamicCGs/pool.dot -- ./patterns/creational/pool.py
pycallgraph graphviz --dot-file dynamicCGs/borg.dot -- ./patterns/creational/borg.py
pycallgraph graphviz --dot-file dynamicCGs/observer.dot -- ./patterns/behavioral/observer.py
pycallgraph graphviz --dot-file dynamicCGs/catalog.dot -- ./patterns/behavioral/catalog.py
pycallgraph graphviz --dot-file dynamicCGs/memento.dot -- ./patterns/behavioral/memento.py
pycallgraph graphviz --dot-file dynamicCGs/command.dot -- ./patterns/behavioral/command.py
pycallgraph graphviz --dot-file dynamicCGs/registry.dot -- ./patterns/behavioral/registry.py
pycallgraph graphviz --dot-file dynamicCGs/mediator.dot -- ./patterns/behavioral/mediator.py
pycallgraph graphviz --dot-file dynamicCGs/strategy.dot -- ./patterns/behavioral/strategy.py
pycallgraph graphviz --dot-file dynamicCGs/visitor.dot -- ./patterns/behavioral/visitor.py
pycallgraph graphviz --dot-file dynamicCGs/iterator.dot -- ./patterns/behavioral/iterator.py
pycallgraph graphviz --dot-file dynamicCGs/specification.dot -- ./patterns/behavioral/specification.py
pycallgraph graphviz --dot-file dynamicCGs/template.dot -- ./patterns/behavioral/template.py
pycallgraph graphviz --dot-file dynamicCGs/chain_of_responsibility.dot -- ./patterns/behavioral/chain_of_responsibility.py
pycallgraph graphviz --dot-file dynamicCGs/publish_subscribe.dot -- ./patterns/behavioral/publish_subscribe.py
pycallgraph graphviz --dot-file dynamicCGs/state.dot -- ./patterns/behavioral/state.py
pycallgraph graphviz --dot-file dynamicCGs/chaining_method.dot -- ./patterns/behavioral/chaining_method.py
pycallgraph graphviz --dot-file dynamicCGs/delegation_pattern.dot -- ./patterns/fundamental/delegation_pattern.py
pycallgraph graphviz --dot-file dynamicCGs/facade.dot -- ./patterns/structural/facade.py
pycallgraph graphviz --dot-file dynamicCGs/proxy.dot -- ./patterns/structural/proxy.py
pycallgraph graphviz --dot-file dynamicCGs/adapter.dot -- ./patterns/structural/adapter.py
pycallgraph graphviz --dot-file dynamicCGs/decorator.dot -- ./patterns/structural/decorator.py
pycallgraph graphviz --dot-file dynamicCGs/flyweight.dot -- ./patterns/structural/flyweight.py
pycallgraph graphviz --dot-file dynamicCGs/bridge.dot -- ./patterns/structural/bridge.py
pycallgraph graphviz --dot-file dynamicCGs/3_tier.dot -- ./patterns/structural/3_tier.py
pycallgraph graphviz --dot-file dynamicCGs/composite.dot -- ./patterns/structural/composite.py
pycallgraph graphviz --dot-file dynamicCGs/front_controller.dot -- ./patterns/structural/front_controller.py
pycallgraph graphviz --dot-file dynamicCGs/flyweight_with_metaclass.dot -- ./patterns/structural/flyweight_with_metaclass.py
pycallgraph graphviz --dot-file dynamicCGs/mvc.dot -- ./patterns/structural/mvc.py
